version: "3"
services:
  app:
    image: heinrian/hs-distributed-systems-lab-todo-backend-spring-boot:latest
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todoapp
      - SPRING_DATASOURCE_USERNAME=todoapp
      - SPRING_DATASOURCE_PASSWORD=password123!
    ports:
      - "8090:8090"

  db:
    image: postgres
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: password123!
      POSTGRES_DB: todoapp